# LegalMind Configuration

# Dataset settings
dataset:
  name: "isaacus/open-australian-legal-qa"
  alternative: "ibunescu/qa_legal_dataset_train"
  local_path: "data/raw/"

# Chunking settings
chunking:
  strategies:
    case_document:
      enabled: true
      description: "Top-level chunking by case document"
    legal_sections:
      enabled: true
      description: "Mid-level chunking by legal reasoning sections (facts, arguments, holding)"
    paragraphs:
      enabled: true
      description: "Paragraph-level chunking for specific legal points"

  chunk_sizes:
    case_holdings:
      min_tokens: 300
      max_tokens: 500
    factual_backgrounds:
      min_tokens: 400
      max_tokens: 600
    legal_reasoning:
      min_tokens: 500
      max_tokens: 700

# Metadata settings
metadata:
  fields:
    - jurisdiction
    - document_type
    - citation
    - url
    - date
    - court

# Embedding settings
embedding:
  model_name: "BAAI/bge-large-en-v1.5"
  #  device: "cuda"  # or "cpu" if GPU not available
  device: "cpu"
  batch_size: 32
  max_length: 512

# Vector database settings
vectordb:
  name: "chroma"
  persist_directory: "data/chroma_db"
  collection_name: "legal_documents"

# LLM settings
llm:
  model_name: "microsoft/phi-2"  # Fallback model if LM Studio is not available
  device: "cpu"  # or "cuda" if GPU available
  temperature: 0.1
  max_new_tokens: 1024
  use_flash_attention: false

# LM Studio API settings
lm_studio:
  api_base_url: "http://127.0.0.1:1234/v1"
  model_id: "phi-4-mini-instruct"  # This is just for display, LM Studio uses whatever model is loaded

# RAG settings
rag:
  basic:
    enabled: true
    top_k: 5
  query_expansion:
    enabled: true
    top_k: 5
    expansion_strategies:
      synonyms: true
      legal_terms: true
      jurisdiction_specific: true
  multi_query:
    enabled: true
    top_k: 6
    max_perspectives: 3
    strategies:
      plaintiff_perspective: true
      defendant_perspective: true
      jurisdictional_perspective: true
      statutory_perspective: true
      case_law_perspective: true
  metadata_enhanced:
    enabled: true
    top_k: 7
    weights:
      similarity: 0.6
      court_hierarchy: 0.2
      recency: 0.2
    strategies:
      jurisdiction_filtering: true
      court_hierarchy_weighting: true
      recency_analysis: true
      citation_network: true
  advanced:
    enabled: true
    top_k: 8
    strategy_selection: "auto"  # Can be "auto", "fixed", or "hybrid"

# RLHF settings
rlhf:
  enabled: true
  reward_model:
    model_name: "distilbert-base-uncased"
    training_epochs: 3
    learning_rate: 2e-5
    batch_size: 8
  feedback:
    feedback_path: "data/feedback"
    min_preference_pairs: 10
  confidence_threshold: 0.7

# Citation handling settings
citation:
  precedent_db_path: "data/precedents/australian_citations.json"
  verification:
    enabled: true
    min_confidence: 0.6
  formatting:
    enabled: true
    add_links: true
  suggestion:
    enabled: true
    relevance_threshold: 0.3

# Hallucination mitigation settings
hallucination:
  enabled: true
  detection:
    check_citations: true
    check_claims: true
    confidence_threshold: 0.7
  mitigation:
    add_disclaimers: true
    replace_citations: true
    modify_claims: true
  crosscheck:
    enabled: true
    australian_precedents: true

# UI settings
ui:
  type: "streamlit"  # or "gradio"
  title: "LegalMind Assistant"
  description: "Your AI assistant for legal information and reasoning"
  theme: "light"
  features:
    confidence_display: true
    citation_validation: true
    hallucination_warning: true
    rag_strategy_display: true
    advanced_rag_options: true

# Evaluation settings
evaluation:
  metrics:
    - relevance
    - correctness
    - citation_accuracy
    - hallucination_rate
  test_set_size: 100